Chapter 01

# 行向量、列向量
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码使用`numpy`库在Python中创建和转置行向量与列向量，演示了向量在不同形态之间的转换过程。这种转换在线性代数中非常重要，特别是在矩阵运算和数据处理过程中。

### 代码细节

1. **行向量转置为列向量**：代码首先定义了一个行向量$a\_\text{row} = [1, 2, 3]$，并通过转置操作`a_row.T`将其转换为列向量$b$。转置后的列向量表示为：

   $$
   b = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}
   $$

   这种转置操作将原来的单行多列矩阵转换为多行单列矩阵。

2. **列向量转置为行向量**：代码接下来定义了一个列向量$b\_\text{col} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$，并通过转置操作`b_col.T`将其转换为行向量$a$。转置后的行向量表示为：

   $$
   a = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
   $$

   这种操作将原来的单列多行矩阵转换为多列单行矩阵。

### 总结

该代码展示了如何通过转置操作在行向量和列向量之间进行切换。行向量与列向量的转置本质上是对矩阵维度的调整，使得数据可以在不同的维度上操作和计算，这在矩阵乘法、线性变换和机器学习数据处理中尤为关键。

## 转置行向量和列向量的操作

In [1]:
import numpy as np  # 导入numpy库

## 定义一个行向量并转置为列向量

In [2]:
a_row = np.array([[1, 2, 3]])  # 定义一个行向量
a_row  # 输出行向量

array([[1, 2, 3]])

In [3]:
b = a_row.T  # 将行向量转置为列向量
b  # 输出列向量

array([[1],
       [2],
       [3]])

## 定义一个列向量并转置为行向量

In [4]:
b_col = np.array([[1], [2], [3]])  # 定义一个列向量
b_col  # 输出列向量

array([[1],
       [2],
       [3]])

In [5]:
a = b_col.T  # 将列向量转置为行向量
a  # 输出行向量

array([[1, 2, 3]])