Chapter 01

# 矩阵
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)



该代码通过`numpy`库创建了一个矩阵$A$，并展示了如何提取该矩阵的特定列和行元素。

1. **矩阵定义**：代码定义了一个$2 \times 3$的矩阵$A$，内容如下：

   $$
   A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
   $$

2. **提取列向量**：
   - `A_first_col`提取矩阵的第一列，存储为一维数组（行向量）：
     $$
     A[:, 0] = [1, 4]
     $$
   - `A_first_col_V2`以列向量的形式提取第一列：
     $$
     A[:, [0]] = \begin{bmatrix} 1 \\ 4 \end{bmatrix}
     $$
   - `A_first_second_col_V2`提取第一列和第二列：
     $$
     A[:, [0, 1]] = \begin{bmatrix} 1 & 2 \\ 4 & 5 \end{bmatrix}
     $$
   - `A_first_third_col_V2`提取第一列和第三列：
     $$
     A[:, [0, 2]] = \begin{bmatrix} 1 & 3 \\ 4 & 6 \end{bmatrix}
     $$

3. **提取行向量**：
   - `A_first_row`提取第一行：
     $$
     A[[0], :] = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
     $$
   - `A_second_row`提取第二行：
     $$
     A[[1], :] = \begin{bmatrix} 4 & 5 & 6 \end{bmatrix}
     $$

4. **提取特定元素**：`A_second_row_first_col`提取矩阵$A$中第二行第一列的元素，即$4$：

   $$
   A[[1], [0]] = 4
   $$

### 总结

该代码展示了如何使用`numpy`对矩阵的行和列进行灵活提取，为矩阵处理中的各种数据提取需求提供了实现方法。这种操作广泛应用于数据分析和科学计算中，特别是在对矩阵数据的选择和变换过程中。

## 使用numpy提取矩阵的不同列和行

In [1]:
import numpy as np  # 导入numpy库

## 定义矩阵A

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 定义2x3矩阵A
A  # 输出矩阵A

array([[1, 2, 3],
       [4, 5, 6]])

## 提取矩阵的不同列

In [3]:
A_first_col = A[:,0]  # 提取矩阵A的第一列（存储为一维行向量）
A_first_col  # 输出第一列

array([1, 4])

In [4]:
A_first_col_V2 = A[:,[0]]  # 提取矩阵A的第一列（存储为列向量）
A_first_col_V2  # 输出第一列（列向量形式）

array([[1],
       [4]])

In [5]:
A_first_second_col_V2 = A[:,[0,1]]  # 提取矩阵A的第一列和第二列
A_first_second_col_V2  # 输出第一列和第二列

array([[1, 2],
       [4, 5]])

In [6]:
A_first_third_col_V2 = A[:,[0,2]]  # 提取矩阵A的第一列和第三列
A_first_third_col_V2  # 输出第一列和第三列

array([[1, 3],
       [4, 6]])

## 提取矩阵的不同行

In [7]:
A_first_row = A[[0],:]  # 提取矩阵A的第一行
A_first_row  # 输出第一行

array([[1, 2, 3]])

In [8]:
A_second_row = A[[1],:]  # 提取矩阵A的第二行
A_second_row  # 输出第二行

array([[4, 5, 6]])

## 提取矩阵A中第二行的第一列元素

In [9]:
A_second_row_first_col = A[[1],[0]]  # 提取矩阵A中位置(i=2, j=1)的元素
A_second_row_first_col  # 输出矩阵A中第二行第一列的元素

array([4])