Chapter 01

# 矩阵加法，向量化运算
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码使用`numpy`库对两个矩阵$A$和$B$进行逐元素相加，并展示了两种方法：直接转换为`numpy`数组相加和使用`numpy`的`add`函数。矩阵逐元素相加是指对于两个大小相同的矩阵，将它们的对应位置的元素分别相加，形成新的矩阵。

### 代码细节

1. **定义矩阵**：代码定义了两个矩阵$A$和$B$，矩阵$A$为：

   $$
   A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
   $$

   矩阵$B$为：

   $$
   B = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \end{bmatrix}
   $$

2. **逐元素相加**：
   - 使用`np.array(A) + np.array(B)`：首先将$A$和$B$转换为`numpy`数组，再进行逐元素相加。结果为：

     $$
     A + B = \begin{bmatrix} 2 & 2 & 3 \\ 4 & 6 & 6 \end{bmatrix}
     $$

   - 使用`np.add(A, B)`：`numpy`的`add`函数用于逐元素相加，得到与前一种方法相同的结果。

### 总结

这段代码展示了在`numpy`中对矩阵进行逐元素相加的便捷性。对于矩阵$A$和$B$的对应位置上的每个元素$A[i][j]$和$B[i][j]$，计算它们的和，得到新的矩阵。这种逐元素相加方式在科学计算和数据处理中特别常见。

## 使用numpy对两个矩阵进行逐元素相加

In [2]:
import numpy as np  # 导入numpy库

In [3]:
A = [[1, 2, 3],  # 定义矩阵A
     [4, 5, 6]]
# A = np.array(A)

In [4]:
B = [[1, 0, 0],  # 定义矩阵B
     [0, 1, 0]]
# B = np.array(B)

## 使用numpy的数组相加方法对矩阵A和矩阵B逐元素相加

In [6]:
print(np.array(A) + np.array(B))  # 将A和B转换为numpy数组并逐元素相加

[[2 2 3]
 [4 6 6]]


## 使用numpy的add函数对矩阵A和矩阵B逐元素相加

In [8]:
print(np.add(A, B))  # 使用numpy的add函数逐元素相加并输出结果

[[2 2 3]
 [4 6 6]]
