Chapter 02

# 向量内积
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码计算了行向量和列向量的点积，展示了向量间的内积（点积）及张量积的应用。点积（内积）是线性代数中基本的运算，用于将两个向量相乘并得到一个标量，而张量积则展示向量之间更复杂的组合关系。

### 代码细节

1. **行向量点积**：
   - 定义行向量 $a\_\text{row} = [1, 2, 3]$ 和 $b\_\text{row} = [4, 3, 2]$。
   - 使用`np.inner`计算两个行向量的点积，点积公式为：

     $$
     a\_\text{dot\_b} = a\_\text{row} \cdot b\_\text{row} = 1 \times 4 + 2 \times 3 + 3 \times 2 = 16
     $$

   - 使用`np.sum(a_row * b_row)`逐元素相乘后求和，得到相同结果$16$。

2. **列向量点积**：
   - 定义列向量 $a\_\text{col} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$ 和 $b\_\text{col} = \begin{bmatrix} -1 \\ 0 \\ 1 \end{bmatrix}$。
   - 使用`np.inner`计算列向量的张量积（tensor product），将$a_\text{col}$和$b_\text{col}$的每个元素成对相乘，结果为一个矩阵。
   - 使用`np.sum(a_col * b_col)`逐元素乘积并求和得到一个标量，计算公式为：

     $$
     \text{sum} = (1 \times -1) + (2 \times 0) + (3 \times 1) = 2
     $$

### 总结

该代码展示了如何计算行向量和列向量的点积及张量积。行向量的点积结果是一个标量，表示向量在相同维度方向上的投影和；列向量张量积的结果是矩阵，显示出各个元素的相互组合。点积和张量积广泛用于线性代数、机器学习和物理计算中，用于表示向量间的关系和相互作用。

## 行向量点积

In [1]:
import numpy as np  # 导入numpy库

In [2]:
a_row = np.array([[1, 2, 3]])  # 定义行向量a_row

In [3]:
b_row = np.array([[4, 3, 2]])  # 定义行向量b_row

In [4]:
a_dot_b = np.inner(a_row, b_row)  # 计算行向量a_row和b_row的点积
print(a_dot_b)  # 输出点积结果

[[16]]


In [5]:
print(np.inner(a_row[:], b_row[:]))  # 使用inner函数计算点积并输出结果

[[16]]


In [6]:
print(np.sum(a_row * b_row))  # 使用逐元素乘积求和计算点积并输出结果

16


## 列向量点积

In [7]:
a_col = np.array([[1], [2], [3]])  # 定义列向量a_col
b_col = np.array([[-1], [0], [1]])  # 定义列向量b_col

In [11]:
a_col.T @ b_col

array([[2]])

In [ ]:
print(np.sum(a_col * b_col))  # 使用逐元素乘积求和计算并输出结果

## 向量张量积

In [8]:
a_dot_b = np.inner(a_col, b_col)  # 计算列向量a_col和b_col的点积（张量积）

In [9]:
print(a_dot_b)  # 输出张量积结果

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [12]:
a_col @ b_col.T

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])