Chapter 02

# 逐项积
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码使用`numpy`库计算了两个行向量和两个矩阵的逐元素乘积（element-wise product），即对同维度向量或矩阵的对应位置的元素逐一相乘，得到一个新的向量或矩阵。

### 代码细节

1. **行向量逐元素乘积**：
   - 定义了两个行向量 $a = [1, 2, 3]$ 和 $b = [4, 5, 6]$。
   - 计算$a$和$b$的逐元素乘积，逐元素乘积的公式为：

     $$
     a\_times\_b = [a[0] \times b[0], a[1] \times b[1], a[2] \times b[2]] = [1 \times 4, 2 \times 5, 3 \times 6] = [4, 10, 18]
     $$

   - 结果为向量$[4, 10, 18]$，表示两个行向量在各个位置上相乘的结果。

2. **矩阵逐元素乘积**：
   - 定义矩阵

     $$
     A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
     $$

     和矩阵

     $$
     B = \begin{bmatrix} 1 & 2 & 3 \\ -1 & 0 & 1 \end{bmatrix}
     $$

   - 逐元素乘积通过将矩阵$A$和$B$的对应元素分别相乘，得到新矩阵$A\_times\_B$：

     $$
     A\_times\_B = \begin{bmatrix} A[0][0] \times B[0][0] & A[0][1] \times B[0][1] & A[0][2] \times B[0][2] \\ A[1][0] \times B[1][0] & A[1][1] \times B[1][1] & A[1][2] \times B[1][2] \end{bmatrix} = \begin{bmatrix} 1 \times 1 & 2 \times 2 & 3 \times 3 \\ 4 \times -1 & 5 \times 0 & 6 \times 1 \end{bmatrix} = \begin{bmatrix} 1 & 4 & 9 \\ -4 & 0 & 6 \end{bmatrix}
     $$

   - 结果矩阵$A\_times\_B$为$\begin{bmatrix} 1 & 4 & 9 \\ -4 & 0 & 6 \end{bmatrix}$。

### 总结

此代码演示了行向量和矩阵的逐元素乘积计算。逐元素乘积广泛用于神经网络中的损失计算、矩阵处理、以及数据操作中的逐项相乘计算，是数值运算中常用的基本操作。

## 行向量的逐元素乘积

In [1]:
import numpy as np  # 导入numpy库

In [2]:
a = np.array([[1, 2, 3]])  # 定义行向量a
a  # 输出行向量a

array([[1, 2, 3]])

In [3]:
b = np.array([[4, 5, 6]])  # 定义行向量b
b  # 输出行向量b

array([[4, 5, 6]])

In [4]:
a_times_b = a * b  # 计算行向量a和b的逐元素乘积
a_times_b  # 输出行向量的逐元素乘积结果

array([[ 4, 10, 18]])

## 矩阵的逐元素乘积

In [5]:
A = np.array([[1, 2, 3],  # 定义矩阵A
              [4, 5, 6]])
A  # 输出矩阵A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
B = np.array([[1, 2, 3],  # 定义矩阵B
              [-1, 0, 1]])
B  # 输出矩阵B

array([[ 1,  2,  3],
       [-1,  0,  1]])

In [7]:
A_times_B = A * B  # 计算矩阵A和B的逐元素乘积
A_times_B  # 输出矩阵的逐元素乘积结果

array([[ 1,  4,  9],
       [-4,  0,  6]])