Chapter 02

# 矩阵乘法
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码使用`numpy`库计算两个矩阵的乘积，并逐项展示了每个元素的计算过程。矩阵乘法是通过行与列的对应元素相乘并求和得到结果矩阵中的每个元素。

### 代码细节

1. **定义矩阵**：
   - 定义矩阵 $A$ 和 $B$：
   
     $$
     A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 4 & 2 \\ 3 & 1 \end{bmatrix}
     $$

2. **矩阵乘法计算**：
   - 计算$A$和$B$的矩阵乘积$C$，结果矩阵$C$的每个元素$C[i,j]$为$A$的第$i$行与$B$的第$j$列的点积。
   - 矩阵乘积的计算公式为：

     $$
     C = A \times B = \begin{bmatrix} A[0,0] \cdot B[0,0] + A[0,1] \cdot B[1,0] & A[0,0] \cdot B[0,1] + A[0,1] \cdot B[1,1] \\ A[1,0] \cdot B[0,0] + A[1,1] \cdot B[1,0] & A[1,0] \cdot B[0,1] + A[1,1] \cdot B[1,1] \end{bmatrix} = \begin{bmatrix} 10 & 4 \\ 24 & 10 \end{bmatrix}
     $$

3. **逐项计算过程**：
   - 第1行、第1列元素：

     $$
     C[0,0] = A[0,0] \times B[0,0] + A[0,1] \times B[1,0] = 1 \times 4 + 2 \times 3 = 10
     $$
   
   - 第1行、第2列元素：

     $$
     C[0,1] = A[0,0] \times B[0,1] + A[0,1] \times B[1,1] = 1 \times 2 + 2 \times 1 = 4
     $$
   
   - 第2行、第1列元素：

     $$
     C[1,0] = A[1,0] \times B[0,0] + A[1,1] \times B[1,0] = 3 \times 4 + 4 \times 3 = 24
     $$
   
   - 第2行、第2列元素：

     $$
     C[1,1] = A[1,0] \times B[0,1] + A[1,1] \times B[1,1] = 3 \times 2 + 4 \times 1 = 10
     $$

### 总结

此代码通过计算矩阵乘法，展示了如何逐项计算结果矩阵$C$中的每个元素。矩阵乘法在许多应用中至关重要，尤其是在线性变换和数据处理领域。最终的结果矩阵$C$表示了矩阵$A$和$B$之间的乘积关系。


## 定义矩阵并计算矩阵乘积

In [1]:
import numpy as np  # 导入numpy库

A = np.array([[1, 2],  # 定义矩阵A
              [3, 4]])
A  # 输出矩阵A

array([[1, 2],
       [3, 4]])

In [2]:
B = np.array([[4, 2],  # 定义矩阵B
              [3, 1]])
B  # 输出矩阵B

array([[4, 2],
       [3, 1]])

In [3]:
C = A @ B  # 计算矩阵A和B的乘积
C  # 输出矩阵乘法结果C

array([[10,  4],
       [24, 10]])

## 逐元素计算矩阵乘法的结果

In [4]:
A[[0]] @ B[:, [0]]  # 第1行和第1列的矩阵乘法结果

array([[10]])

In [5]:
A[[0]] @ B[:, [1]]  # 第1行和第2列的矩阵乘法结果

array([[4]])

In [6]:
A[[1]] @ B[:, [0]]  # 第2行和第1列的矩阵乘法结果

array([[24]])

In [7]:
A[[1]] @ B[:, [1]]  # 第2行和第2列的矩阵乘法结果

array([[10]])