Chapter 02

# 矩阵标量乘法
Book_3《数学要素》 | 鸢尾花书：从加减乘除到机器学习 (第二版)

该代码使用`numpy`库定义了一个列向量、一个行向量和一个矩阵，并分别对它们执行标量乘法操作。标量乘法是一种基本的线性代数运算，即将向量或矩阵的每个元素与同一数相乘。

### 代码细节

1. **列向量标量乘法**：定义列向量

   $$
   a_\text{col} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}
   $$

   将该向量与标量$2$相乘，得到新的列向量

   $$
   b_\text{col} = 2 \times a_\text{col} = \begin{bmatrix} 2 \\ 4 \\ 6 \end{bmatrix}
   $$

2. **行向量标量乘法**：定义行向量

   $$
   a_\text{row} = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
   $$

   将该向量与标量$2$相乘，结果为

   $$
   b_\text{row} = 2 \times a_\text{row} = \begin{bmatrix} 2 & 4 & 6 \end{bmatrix}
   $$

3. **矩阵标量乘法**：定义矩阵

   $$
   A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
   $$

   通过将每个元素与$2$相乘，得到新矩阵

   $$
   B = 2 \times A = \begin{bmatrix} 2 & 4 & 6 \\ 8 & 10 & 12 \end{bmatrix}
   $$

### 总结

这段代码展示了列向量、行向量和矩阵的标量乘法。通过这种操作，可以将向量和矩阵中的每个元素同时放大或缩小，这在数据缩放、线性变换和各种线性代数运算中具有广泛应用。

## 定义并操作列向量

In [1]:
import numpy as np  # 导入numpy库

In [2]:
a_col = np.array([[1], [2], [3]])  # 定义列向量a_col
a_col  # 输出列向量a_col

array([[1],
       [2],
       [3]])

In [3]:
b_col = 2 * a_col  # 将列向量a_col乘以2得到新列向量b_col
b_col  # 输出新列向量b_col

array([[2],
       [4],
       [6]])

## 定义并操作行向量

In [4]:
a_row = np.array([[1, 2, 3]])  # 定义行向量a_row
a_row  # 输出行向量a_row

array([[1, 2, 3]])

In [5]:
b_row = 2 * a_row  # 将行向量a_row乘以2得到新行向量b_row
b_row  # 输出新行向量b_row

array([[2, 4, 6]])

## 定义并操作矩阵

In [6]:
A = np.array([[1, 2, 3],  # 定义矩阵A
              [4, 5, 6]])
A  # 输出矩阵A

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
B = 2 * A  # 将矩阵A乘以2得到新矩阵B
B  # 输出新矩阵B

array([[ 2,  4,  6],
       [ 8, 10, 12]])